#!/usr/bin/env python3
"""Write formalization/PAPER_MAP.md from formalization/lean-verification.json.

The map lists, for every paper label cited in a Lean docstring, the Lean theorems that cite it,
grouped by the TeX file that defines the label and ordered as the labels appear in the paper.
Run `python3 formalization/verify.py` first; it records the label-to-theorem map.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FORMAL = ROOT / "formalization"
PAPER = ROOT / "paper"
sys.path.insert(0, str(FORMAL))

import verify  # noqa: E402

KIND = {
    "thm": "Theorem",
    "lem": "Lemma",
    "prop": "Proposition",
    "cor": "Corollary",
    "eq": "Equation",
    "sec": "Section",
    "app": "Appendix",
    "rem": "Remark",
    "def": "Definition",
}


def document_order() -> list[Path]:
    """Compiled TeX files in reading order: the conference version, then the full version."""
    seen: list[Path] = []

    def visit(path: Path) -> None:
        if path in seen or not path.exists():
            return
        seen.append(path)
        text = re.sub(r"(?<!\\)%.*", "", path.read_text())
        for name in re.findall(r"\\(?:input|include)\{([^}]+)\}", text):
            child = PAPER / name
            visit(child if child.suffix == ".tex" else child.with_suffix(".tex"))

    for entry in verify.ENTRY_POINTS:
        visit(PAPER / entry)
    return seen


def label_titles() -> dict[str, str]:
    """Optional bracketed titles of labelled environments, e.g. [One-row cost]."""
    titles = {}
    for path in verify.compiled_tex():
        text = path.read_text()
        for m in re.finditer(r"\\begin\{\w+\}\[([^\]]*)\]\s*\\label\{([^}]+)\}", text):
            titles[m.group(2)] = re.sub(r"\s+", " ", m.group(1)).strip()
        for m in re.finditer(r"\\(?:sub)*section\*?\{([^}]*)\}\s*\\label\{([^}]+)\}", text):
            titles[m.group(2)] = re.sub(r"\s+", " ", m.group(1)).strip()
    return titles


def main() -> int:
    report = json.loads((FORMAL / "lean-verification.json").read_text())
    cited: dict[str, list[str]] = report["labels"]
    order: list[tuple[str, str]] = []
    for path in document_order():
        text = re.sub(r"(?<!\\)%.*", "", path.read_text())
        for label in re.findall(r"\\label\{([^}]+)\}", text):
            if label in cited and all(label != seen for _, seen in order):
                order.append((path.name, label))
    titles = label_titles()
    lines = [
        "# Paper results and their Lean theorems",
        "",
        "Generated by `tools/lean_map.py` from `lean-verification.json`. Each row lists the",
        "Lean theorems whose docstrings cite the paper label. A citation means the theorem",
        "formalizes that statement or a step of its proof; the docstring says which, and the",
        "module header lists what is not formalized. Paper labels are stable across versions;",
        "theorem numbers are not, so the map uses labels.",
        "",
        f"Audited theorems: {report['user_theorems']}. Paper labels cited: "
        f"{report['paper_labels_cited']}.",
    ]
    current = None
    for fname, label in order:
        if fname != current:
            lines += ["", f"## `{fname}`", "", "| Label | Lean theorems |", "|---|---|"]
            current = fname
        prefix = label.split(":", 1)[0]
        name = KIND.get(prefix, prefix)
        title = titles.get(label)
        head = f"`{label}`" + (f" ({name}: {title})" if title else f" ({name})")
        names = ", ".join(f"`{n.removeprefix('ExactSampling.')}`" for n in sorted(cited[label]))
        lines.append(f"| {head} | {names} |")
    (FORMAL / "PAPER_MAP.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {FORMAL / 'PAPER_MAP.md'} with {len(order)} labels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
